### ISSUE TITLE
Error 200

### ISSUE THREAD

**Issue by snipfou** [innovation-system/electron-kiosk#5]
![image](https://user-images.githubusercontent.com/91960500/223773617-5b7fc394-6598-4bbe-bb57-c7c071b8aafd.png)

I am getting this error while trying to load any website, any idea why ? thank you :)

**Comment by robertsLando** [comment]
ATM when the application starts it checks for the url availability, until it is not available it shows a loader to prevent showind the classic chrome 404 error page, in your case that site doesn't support cors requests so the url check request fails

In order to fix that we need to fix the [checkUrl](https://github.com/innovation-system/electron-kiosk/blob/main/src/App.vue#L202) method in App.vue in order to make it work also with cors
